spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /test_db  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb   #접속 URL
    username: test  # 사용자 이름 (로그인 시 사용)
    password: 1234  # 사용자 암호 (로그인 시 사용)

#mybatis:
#  config-location: classpath:mybatis/config/mybatis-config.xml
#  configuration:
#    cache-enabled: true
#    use-generated-keys: true
#    default-executor-type: reuse
#    default-statement-timeout: 3000